# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ae17d6066c12d019dcd33ce1eb8a574e"
application_url = "https://mystery-box.proxipreview.com"
embedded = true
name = "mystery-box"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_discounts,write_app_proxy,read_publications,write_publications,read_cart_transforms,write_cart_transforms"

[app_proxy]
url = "/apps/giftlab"
subpath = "giftlab"
prefix = "apps"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products"
  topics = [ "products/create", "products/update", "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory-levels-update"
  topics = [ "inventory_levels/update" ]

[auth]
redirect_urls = [
  "https://mystery-box.proxipreview.com/auth/callback",
  "https://mystery-box.proxipreview.com/auth/shopify/callback",
  "https://mystery-box.proxipreview.com/api/auth/callback",
]

[build]
automatically_update_urls_on_dev = false
