# Use this configuration only after Protected Customer Data access has been
# enabled for the app in Shopify's Dev/Partner Dashboard.

client_id = "ae17d6066c12d019dcd33ce1eb8a574e"
application_url = "https://example.com"
embedded = true
name = "mystery-box"

[access_scopes]
scopes = "read_products,read_inventory,read_orders,read_customers,write_discounts,write_app_proxy"

[app_proxy]
url = "/apps/giftlab"
subpath = "giftlab"
prefix = "apps"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products"
  topics = [ "products/create", "products/update", "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory-levels-update"
  topics = [ "inventory_levels/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders-create"
  topics = [ "orders/create" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
