api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "giftlab-gift-transform"
type = "function"
uid = "183b0da2-4e3b-fb8e-bc40-c8a9c9a81350396de8bd"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/giftlab-gift-transform.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
